[package]
name = "typeit_server"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.2"
rocket = "0.5.0-rc.1"
rocket_codegen = "0.5.0-rc.1"
tokio = { version = "1", features = ["full"] }

[lib]
name = "typeit_server"
crate-type = ["cdylib"]
